name: Feature suggestion
description: Suggest a feature relevant to legacy 1.8.9/anarchy hardening use
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature description
      description: Describe the feature and why it should be added.
    validations:
      required: true
