name: Legacy compatibility bug or other issue
description: Report a bug, compatibility issue, or legacy behavior regression
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug and how to replicate it
      description: A video or detailed instructions to help replicate the issue would help.
      placeholder: |
        Step 1. Do this
        Step 2. Then do this
        Step 3. etc...
    validations:
      required: true

  - type: textarea
    attributes:
      label: GrimLegacy fork version
      description: Provide the version of this GrimLegacy fork running on the server. You can run `/grim version` to check.
      placeholder: Examples include 2.3.73-8ddd7f1, 2.3.72, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Server version
      description: |
        Run `/version` and provide server software/build + Minecraft version (include if this is a 1.8.8/1.8.9 stack).
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Affected Platform(s)
      description: Which platforms does this issue affect? If you aren't sure, select both.
      options:
        - "Bukkit (primary target)"
        - "Fabric (not primary target)"
      multiple: true
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugins/Mods
      description: |
        List all plugins or mods installed on your server. To list plugins on Bukkit-based servers, run `/plugins`.
        If your server is behind a proxy such as Bungeecord, you should list the proxy's plugins as well.
    validations:
      required: true
